version: '3.8'

services:

  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_DATABASE=misistema
      - MYSQL_PASSWORD=311034
      - MYSQL_ROOT_PASSWORD=311034
      - MYSQL_HOST=mysql_db
      - APP_ENV=local
      - APP_KEY=base64:tu_clave_aqui
      - APP_DEBUG=true
      - MYSQL_USER=root
      - APP_URL=http://localhost
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - piamond_network

volumes:
  mysql_data:


networks:
  piamond_network:
    driver: bridge
